repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
  args: ["--config-file=pyproject.toml", "--strict"]
  files: ^(src/reactor/(analysis\.py|energy\.py|metrics\.py)|scripts/(envelope_sweep|performance_budget|kpi_diff|generate_progress_dashboard|ndjson_to_csv|plot_envelope_dual_panel|generate_timeline_anomalies|bench_step_loop)\.py)$
  additional_dependencies: []
