[tool.ruff]
line-length = 100
extend-exclude = ["notebooks/**/*.ipynb", "**/*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I", "A", "B", "C4"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = false
no_implicit_optional = true
allow_redefinition = true
show_error_codes = true
strict_optional = true
