name: Build Paper PDF

on:
  workflow_dispatch:
  push:
    paths:
      - 'papers/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'scripts/**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TeX Live packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended \
            texlive-science latexmk latex-plain-dev || true
        shell: bash
      - name: Compile LaTeX (phase3_stability.tex)
        run: |
          set -euo pipefail
          cd papers
          # capture output to build.log for debugging and always produce that artifact
          echo "Building LaTeX: $(pwd)/phase3_stability.tex"
          if command -v latexmk >/dev/null 2>&1; then
            latexmk -pdf -interaction=nonstopmode -halt-on-error phase3_stability.tex 2>&1 | tee build.log
          else
            pdflatex -interaction=nonstopmode phase3_stability.tex 2>&1 | tee build.log || true
          fi
          # show summary
          ls -l
        shell: bash
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: phase3_stability-pdf
          path: papers/phase3_stability.pdf
      - name: Upload LaTeX build log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: phase3_stability-build-log
          path: papers/build.log

  # zenodo-publish removed: publishing requires secrets and caused workflow validation failures
  # zenodo-publish removed (use scripts/publish_zenodo.sh locally or in a guarded CI job)
