name: Build Paper PDF

on:
  workflow_dispatch:
  push:
    paths:
      - 'papers/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'scripts/**'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use stable LaTeX action to build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: papers/phase3_stability.tex
          build_args: -interaction=nonstopmode
          # cache TeX Live packages between runs for speed
          extra_packages: |
            latexmk
            etoolbox
            lmodern
            xetex
        env:
          # ensure non-interactive
          LATEXMK: "latexmk"
      - name: Save action-provided build log (if any)
        if: always()
        run: |
          # the action writes to ./latex.log in its workspace; copy to papers/build.log if present
          if [ -f latex.log ]; then mkdir -p papers; cp latex.log papers/build.log; fi
          # also list produced PDFs
          ls -l papers || true
        shell: bash
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: phase3_stability-pdf
          path: papers/phase3_stability.pdf
      - name: Upload LaTeX build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase3_stability-build-log
          path: papers/build.log

  # zenodo-publish removed: publishing requires secrets and caused workflow validation failures
  # zenodo-publish removed (use scripts/publish_zenodo.sh locally or in a guarded CI job)
