name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build artifacts (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scripts/demo_runner.py --scenario examples/scenario_min.json --steps 10 --dt 1e-3
          python scripts/generate_feasibility_report.py --gamma-series "[150,150,150,150]" --dt 0.002 --b-series "[5,5,5,5]" --E-mag "[0,1,2,3]" --out feasibility_gates_report.json --scenario-id release
          python scripts/run_report.py --feasibility feasibility_gates_report.json --integrated-out integrated_report.json
          python scripts/production_kpi.py --feasibility feasibility_gates_report.json --out production_kpi.json
          python scripts/generate_progress_dashboard.py --docs-dir docs --out progress_dashboard.html --json-out progress_dashboard.json
          # Update baseline KPI for tagged release
          if [ -f production_kpi.json ]; then cp -f production_kpi.json baseline_kpi.json; fi
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            integrated_report.json
            production_kpi.json
            baseline_kpi.json
            feasibility_gates_report.json
            progress_dashboard.html
            progress_dashboard.json
